### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by QarthO** [Simplexity-Development/SimplePlayerFreeze#1]
Love the plugin and how configurable everything is!

I would love to see a ``/freeze all``, (would also need an ``/unfreeze all``) that would freeze all online players, (excluding players with the ``spf.bypass`` permission)

I typically run events, and like freezing everyone at the start/end of the events so this feature would be really helpful! Thanks

**Comment by RhythmicSys** [comment]
I like this idea, trying to mentally work out how I'd go about implementing it though. Will take me a bit to figure out a good way to handle it, since events usually have quite a lot more people than usual, I don't have a good way to test how well freezing and releasing people at the same time would work.

**Comment by QarthO** [comment]
Shouldn't be too complicated, you should be able to just loop through all online players. you can put this in your command class right after line 25

```java
// in the freeze command class
if(strings[0].equalsIgnoreCase("all") || strings[0].equalsIgnoreCase("*")) {
    for(Player player : Bukkit.getOnlinePlayers())
        if(!player.hasPermission(Util.freezeBypassPermission))
            FreezeFunctionality.setFrozen(player);
    return;
}
```
The concern of having everyone being frozen/unfrozen at the exact same time isnt really a concern here. This is all happening on the main thread, so all of this will occur on the same tick.

**Comment by QarthO** [comment]
You could even allow for more customization if you wanted. Making a separate command such as ``/freezeall [world]``  with world being an optional parameter. Without giving world if would do the above code snippet in my previous comment. However if there was a world parameter given it would only freeze the players in that world.

```java
// strings[0] in this case would be the world name
for(Player player : Bukkit.getOnlinePlayers()) {
    if(!player.getWorld().getName().equalsIgnoreCase(strings[0])) continue;
    if(!player.hasPermission(Util.freezeBypassPermission))
        FreezeFunctionality.setFrozen(player);
}
```

**Comment by RhythmicSys** [comment]
https://modrinth.com/plugin/simple-player-freeze/version/2.2.0
This adds the `/freezeall [world]` command, let me know if there are any issues with it!
